/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import consultas.ConsultasPiezas;
import consultas.ConsultasProveedores;
import hibernate_bd.ProveedoresEntity;
import scrollbar.ScrollBarCustom;
import table.TableHeader;

/**
 *
 * @author leiii
 */
public class ConsultaProveedores extends javax.swing.JPanel {

    String[] nombreColumnas = {"Código", "Nombre", "Apellido", "Estado"};
    TableRowSorter<DefaultTableModel> sorter;
    JPanel panel;
    /**
     * Creates new form ConsultaProveedores
     */
    public ConsultaProveedores(JPanel panel) {
        initComponents();

        this.panel = panel;
        tablaProveedores.setShowHorizontalLines(true);
        tablaProveedores.setGridColor(new Color(230,230,230));
        tablaProveedores.setRowHeight(27);
        tablaProveedores.getTableHeader().setReorderingAllowed(true);
        tablaProveedores.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                TableHeader header = new TableHeader(value + "");
                if(column==4){
                    header.setHorizontalAlignment(JLabel.CENTER);
                }
                return header;
            }
       });
       jScrollPane1.getViewport().setBackground(Color.WHITE);
       jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
       fixtable(jScrollPane1);
       cargarDatos();
       
       opcionBusqueda.addItem("Codigo");
       opcionBusqueda.addItem("Nombre");
       opcionBusqueda.addItem("Direccion");
    }
    
    public void fixtable(JScrollPane scroll) {
        scroll.getViewport().setBackground(Color.WHITE);
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        JPanel p = new JPanel();
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        scroll.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    public void cargarDatos() {
        ConsultasProveedores consultasProveedores = new ConsultasProveedores();
        List<ProveedoresEntity> proveedores = new ArrayList<ProveedoresEntity>();
        proveedores = consultasProveedores.recuperarDatosProveedores();
        int cantidad = proveedores.size();
        String[][] d = new String[cantidad][4];
        for (int i = 0; i < proveedores.size(); i++) {
            d[i][0] = String.valueOf(proveedores.get(i).getCodigo());
            d[i][1] = String.valueOf(proveedores.get(i).getNombre());
            d[i][2] = String.valueOf(proveedores.get(i).getApellidos());
            d[i][3] = String.valueOf(proveedores.get(i).getEstado());
        }
        //se carga el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel(d, nombreColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaProveedores.setModel(modelo);
        tablaProveedores.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(modelo);
        tablaProveedores.setRowSorter(sorter);
        consultasProveedores.cerrarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        opcionBusqueda = new javax.swing.JComboBox<>();
        textBusqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonVer = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProveedores.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tablaProveedores.setForeground(new java.awt.Color(102, 102, 102));
        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProveedores.setSelectionBackground(new java.awt.Color(224, 255, 255));
        tablaProveedores.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tablaProveedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 56, 640, 370));

        jLabel1.setText("Filtrar por:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(opcionBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 14, 180, -1));

        textBusqueda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textBusqueda.setBorder(null);
        textBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textBusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(textBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 280, -1));

        jLabel2.setText("Buscar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        botonVer.setBackground(new java.awt.Color(0, 204, 204));
        botonVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVerMousePressed(evt);
            }
        });

        label.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Ver Proovedor");

        javax.swing.GroupLayout botonVerLayout = new javax.swing.GroupLayout(botonVer);
        botonVer.setLayout(botonVerLayout);
        botonVerLayout.setHorizontalGroup(
            botonVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        botonVerLayout.setVerticalGroup(
            botonVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(botonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 120, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 280, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerMousePressed
        if (tablaProveedores.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Para ver más información debes seleccionar un proveedor en la tabla");
        } else {
            String cod = tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 0).toString();
            VerProveedor frame = new VerProveedor(panel, cod);
            frame.setSize(700,490);
            frame.setLocation(0,0);
            panel.removeAll();
            panel.add(frame, BorderLayout.CENTER);
            panel.revalidate();
            panel.repaint();
        }
    }//GEN-LAST:event_botonVerMousePressed

    private void textBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBusquedaKeyReleased
        sorter.setRowFilter(RowFilter.regexFilter("(?i)"+textBusqueda.getText(), opcionBusqueda.getSelectedIndex()));
    }//GEN-LAST:event_textBusquedaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label;
    private javax.swing.JComboBox<String> opcionBusqueda;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField textBusqueda;
    // End of variables declaration//GEN-END:variables
}
