/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import consultas.ConsultasGestion;
import consultas.ConsultasPiezas;
import consultas.ConsultasProveedores;
import consultas.ConsultasProyectos;
import hibernate_bd.GestionEntity;
import hibernate_bd.PiezasEntity;
import hibernate_bd.ProveedoresEntity;
import hibernate_bd.ProyectosEntity;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author leiii
 */
public class EditarGestion extends javax.swing.JPanel {

    JPanel panel;
    List<ProveedoresEntity> proveedores;
    List<ProyectosEntity> proyectos;
    List<PiezasEntity> piezas;
    String codigo;
    
    /**
     * Creates new form EditarGestion
     */
    public EditarGestion(JPanel panel, String codigo) {
        initComponents();
        
        this.panel = panel;
        this.codigo = codigo;

        ConsultasGestion consultasGestion = new ConsultasGestion();
        GestionEntity gestion = consultasGestion.recuperarGestion(codigo);
        cantidad.setText(String.valueOf(gestion.getCantidad()));
        ConsultasProyectos consultasProyectos = new ConsultasProyectos();
        proyectos = consultasProyectos.cargarAltas();
        consultasProyectos.cerrarConexion();
        ConsultasProveedores consultasProveedores = new ConsultasProveedores();
        proveedores = consultasProveedores.cargarAltas();
        consultasProveedores.cerrarConexion();
        ConsultasPiezas consultasPiezas = new ConsultasPiezas();
        piezas = consultasPiezas.cargarAltas();
        consultasPiezas.cerrarConexion();
        if (proyectos.size() == 0 || proveedores.size() == 0 || piezas.size() == 0) {
            JOptionPane.showMessageDialog(null, "Para crear una gestión se necesita una pieza, un proveedor y un proyecto");
            GestionPedidos frame = new GestionPedidos(panel);
            frame.setSize(700, 490);
            frame.setLocation(0, 0);
            panel.removeAll();
            panel.add(frame, BorderLayout.CENTER);
            panel.revalidate();
            panel.repaint();
        }else {
            int proyectoSele = -1;
            int proveSele = -1;
            int piezaSele = -1;
            for (int i = 0; i < proyectos.size(); i++) {
                codProyecto.addItem(proyectos.get(i).getCodigo());
                if (proyectos.get(i).getCodigo().equals(gestion.getProyectosByCodproyecto().getCodigo())) {
                    proyectoSele = i;
                }
            }
            for (int i = 0; i < proveedores.size(); i++) {
                codProveedor.addItem(proveedores.get(i).getCodigo());
                if (proveedores.get(i).getCodigo().equals(gestion.getProveedoresByCodproveedor().getCodigo())) {
                    proveSele = i;
                }
            }
            for (int i = 0; i < piezas.size(); i++) {
                codPieza.addItem(piezas.get(i).getCodigo());
                if (piezas.get(i).getCodigo().equals(gestion.getPiezasByCodpieza().getCodigo())) {
                    piezaSele = i;
                }
            }

            codigoGestion.setText(codigo);
            codPieza.setSelectedIndex(piezaSele);
            codProyecto.setSelectedIndex(proyectoSele);
            codProveedor.setSelectedIndex(proveSele);
            cantidad.setText(String.valueOf(gestion.getCantidad()));
            estado.addItem("ALTA");
            estado.addItem("BAJA");
            if (gestion.getEstado().equals("ALTA")) {
                estado.setSelectedIndex(0);
            } else {
                estado.setSelectedIndex(1);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonEditar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        botonCancelar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        codProveedor = new javax.swing.JComboBox<>();
        infoProyecto = new javax.swing.JTextField();
        codPieza = new javax.swing.JComboBox<>();
        infoProveedor = new javax.swing.JTextField();
        infoPieza = new javax.swing.JTextField();
        codProyecto = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        codigoGestion = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 117, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDITAR GESTIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Proveedor: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pieza: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Proyecto: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Cantidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        botonEditar.setBackground(new java.awt.Color(0, 204, 204));
        botonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEditarMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Editar Gestión");

        javax.swing.GroupLayout botonEditarLayout = new javax.swing.GroupLayout(botonEditar);
        botonEditar.setLayout(botonEditarLayout);
        botonEditarLayout.setHorizontalGroup(
            botonEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonEditarLayout.setVerticalGroup(
            botonEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 160, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 370, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 370, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 370, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 120, 10));

        botonCancelar.setBackground(new java.awt.Color(0, 117, 153));
        botonCancelar.setPreferredSize(new java.awt.Dimension(170, 30));
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCancelarMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cancelar");

        javax.swing.GroupLayout botonCancelarLayout = new javax.swing.GroupLayout(botonCancelar);
        botonCancelar.setLayout(botonCancelarLayout);
        botonCancelarLayout.setHorizontalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonCancelarLayout.setVerticalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonCancelarLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 160, 30));

        codProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(codProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 100, -1));

        infoProyecto.setEditable(false);
        infoProyecto.setBackground(new java.awt.Color(255, 255, 255));
        infoProyecto.setText("<html><p></p></html>");
        infoProyecto.setBorder(null);
        jPanel1.add(infoProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 285, 240, 60));

        codPieza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(codPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, -1));

        infoProveedor.setEditable(false);
        infoProveedor.setBackground(new java.awt.Color(255, 255, 255));
        infoProveedor.setText("<html><p></p></html>");
        infoProveedor.setBorder(null);
        jPanel1.add(infoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 105, 240, 60));

        infoPieza.setEditable(false);
        infoPieza.setBackground(new java.awt.Color(255, 255, 255));
        infoPieza.setText("<html><p></p></html>");
        infoPieza.setBorder(null);
        jPanel1.add(infoPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 195, 240, 60));

        codProyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(codProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 100, -1));

        cantidad.setBorder(null);
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 120, -1));

        jLabel8.setText("Estado:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 120, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 120, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 130, 10));

        jLabel9.setText("Código gestión:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        codigoGestion.setEditable(false);
        codigoGestion.setBackground(new java.awt.Color(255, 255, 255));
        codigoGestion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codigoGestion.setBorder(null);
        jPanel1.add(codigoGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMousePressed
        GestionPedidos frame = new GestionPedidos(panel);
        frame.setSize(700,490);
        frame.setLocation(0,0);
        panel.removeAll();
        panel.add(frame, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_botonCancelarMousePressed

    private void botonEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMousePressed
        try {
            int cantidadNum = Integer.parseInt(cantidad.getText());
            if (cantidad.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos para poder editar");
            } else {
                ConsultasGestion consultasGestion = new ConsultasGestion();
                String estadoText;
                if (estado.getSelectedIndex() == 0) {
                    estadoText = "ALTA";
                } else {
                    estadoText = "BAJA";
                }
                if (consultasGestion.modificarGestion(codigoGestion.getText().toUpperCase(), codProveedor.getSelectedItem().toString(), codPieza.getSelectedItem().toString(), codProyecto.getSelectedItem().toString(), cantidadNum, estadoText, piezas, proyectos, proveedores)) {
                    consultasGestion.cerrarConexion();
                    GestionPiezas frame = new GestionPiezas(panel);
                    frame.setSize(700, 490);
                    frame.setLocation(0, 0);
                    panel.removeAll();
                    panel.add(frame, BorderLayout.CENTER);
                    panel.revalidate();
                    panel.repaint();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio debe ser un número");
        }
    }//GEN-LAST:event_botonEditarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonCancelar;
    private javax.swing.JPanel botonEditar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> codPieza;
    private javax.swing.JComboBox<String> codProveedor;
    private javax.swing.JComboBox<String> codProyecto;
    private javax.swing.JTextField codigoGestion;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JTextField infoPieza;
    private javax.swing.JTextField infoProveedor;
    private javax.swing.JTextField infoProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
