/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author leiii
 */
public class GestionGlobal extends javax.swing.JPanel {

    JPanel pane;
    /**
     * Creates new form GestionGlobal
     */
    public GestionGlobal(JPanel panel) {
        initComponents();

        this.pane = panel;
        
        GestionPedidos frame = new GestionPedidos(panel_global);
        frame.setSize(700,490);
        frame.setLocation(0,0);
        panel_global.removeAll();
        panel_global.add(frame, BorderLayout.CENTER);
        panel_global.revalidate();
        panel_global.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        botonGestion = new javax.swing.JPanel();
        labelGestion = new javax.swing.JLabel();
        botonSuminProveedor = new javax.swing.JPanel();
        labelSuminProveedores = new javax.swing.JLabel();
        botonSuminPiezas = new javax.swing.JPanel();
        labelSuminPiezas = new javax.swing.JLabel();
        panel_global = new javax.swing.JPanel();
        botonEstadisticas = new javax.swing.JPanel();
        labelEstadisticas = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 117, 153));
        jSeparator1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        botonGestion.setBackground(new java.awt.Color(255, 255, 255));
        botonGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonGestionMousePressed(evt);
            }
        });
        botonGestion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelGestion.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelGestion.setForeground(new java.awt.Color(0, 117, 153));
        labelGestion.setText("Piezas, Proveedores y Proyectos");
        botonGestion.add(labelGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(botonGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        botonSuminProveedor.setBackground(new java.awt.Color(255, 255, 255));
        botonSuminProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSuminProveedorMousePressed(evt);
            }
        });
        botonSuminProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSuminProveedores.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelSuminProveedores.setForeground(new java.awt.Color(0, 204, 204));
        labelSuminProveedores.setText("Suministros por Proveedor");
        botonSuminProveedor.add(labelSuminProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel1.add(botonSuminProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 190, 40));

        botonSuminPiezas.setBackground(new java.awt.Color(255, 255, 255));
        botonSuminPiezas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSuminPiezasMousePressed(evt);
            }
        });
        botonSuminPiezas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSuminPiezas.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelSuminPiezas.setForeground(new java.awt.Color(0, 204, 204));
        labelSuminPiezas.setText("Suministros por Piezas");
        botonSuminPiezas.add(labelSuminPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(botonSuminPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 40));

        panel_global.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_globalLayout = new javax.swing.GroupLayout(panel_global);
        panel_global.setLayout(panel_globalLayout);
        panel_globalLayout.setHorizontalGroup(
            panel_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panel_globalLayout.setVerticalGroup(
            panel_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanel1.add(panel_global, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 700, 490));

        botonEstadisticas.setBackground(new java.awt.Color(255, 255, 255));
        botonEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEstadisticasMousePressed(evt);
            }
        });
        botonEstadisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEstadisticas.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelEstadisticas.setForeground(new java.awt.Color(0, 204, 204));
        labelEstadisticas.setText("Estadísticas");
        botonEstadisticas.add(labelEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel1.add(botonEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGestionMousePressed
        darColor(labelGestion);
        devolverColor(labelSuminPiezas);
        devolverColor(labelSuminProveedores);
        devolverColor(labelEstadisticas);

        GestionPedidos frame = new GestionPedidos(panel_global);
        frame.setSize(700,490);
        frame.setLocation(0,0);
        panel_global.removeAll();
        panel_global.add(frame, BorderLayout.CENTER);
        panel_global.revalidate();
        panel_global.repaint();
    }//GEN-LAST:event_botonGestionMousePressed

    private void botonSuminProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSuminProveedorMousePressed
        darColor(labelSuminProveedores);
        devolverColor(labelGestion);
        devolverColor(labelSuminPiezas);
        devolverColor(labelEstadisticas);

        SuministrosProveedor frame = new SuministrosProveedor();
        frame.setSize(700,490);
        frame.setLocation(0,0);
        panel_global.removeAll();
        panel_global.add(frame, BorderLayout.CENTER);
        panel_global.revalidate();
        panel_global.repaint();
    }//GEN-LAST:event_botonSuminProveedorMousePressed

    private void botonSuminPiezasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSuminPiezasMousePressed
        darColor(labelSuminPiezas);
        devolverColor(labelGestion);
        devolverColor(labelSuminProveedores);
        devolverColor(labelEstadisticas);

        SuminstrosPiezas frame = new SuminstrosPiezas();
        frame.setSize(700,490);
        frame.setLocation(0,0);
        panel_global.removeAll();
        panel_global.add(frame, BorderLayout.CENTER);
        panel_global.revalidate();
        panel_global.repaint();
    }//GEN-LAST:event_botonSuminPiezasMousePressed

    private void botonEstadisticasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstadisticasMousePressed
        darColor(labelEstadisticas);
        devolverColor(labelGestion);
        devolverColor(labelSuminProveedores);
        devolverColor(labelSuminPiezas);
        
        Estadisticas frame = new Estadisticas();
        frame.setSize(700,490);
        frame.setLocation(0,0);
        panel_global.removeAll();
        panel_global.add(frame, BorderLayout.CENTER);
        panel_global.revalidate();
        panel_global.repaint();
    }//GEN-LAST:event_botonEstadisticasMousePressed

    private void darColor(JLabel label) {
        label.setForeground(new Color(0, 117, 153));
    }
    
    private void devolverColor(JLabel label) {
        label.setForeground(new Color(0, 204, 204));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonEstadisticas;
    private javax.swing.JPanel botonGestion;
    private javax.swing.JPanel botonSuminPiezas;
    private javax.swing.JPanel botonSuminProveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelEstadisticas;
    private javax.swing.JLabel labelGestion;
    private javax.swing.JLabel labelSuminPiezas;
    private javax.swing.JLabel labelSuminProveedores;
    private javax.swing.JPanel panel_global;
    // End of variables declaration//GEN-END:variables
}
