/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

/**
 *
 * @author leiii
 */
public class SuminstrosPiezas extends javax.swing.JPanel {

    /**
     * Creates new form SuminstrosPiezas
     */
    public SuminstrosPiezas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        codPieza = new javax.swing.JComboBox<>();
        infoPieza = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numProveedores = new javax.swing.JTextField();
        numProyectos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProyectos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        totalPiezas = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pieza:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 50, -1));

        add(codPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 100, -1));

        infoPieza.setEditable(false);
        infoPieza.setBackground(new java.awt.Color(255, 255, 255));
        infoPieza.setText("<html><p></p></html>");
        infoPieza.setBorder(null);
        add(infoPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 240, 60));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 370, 20));

        jLabel1.setText("Nº de proyectos:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setText("Nº de proveedores:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        numProveedores.setEditable(false);
        numProveedores.setBackground(new java.awt.Color(255, 255, 255));
        numProveedores.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numProveedores.setBorder(null);
        add(numProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 50, -1));

        numProyectos.setEditable(false);
        numProyectos.setBackground(new java.awt.Color(255, 255, 255));
        numProyectos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numProyectos.setBorder(null);
        add(numProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, -1));

        tablaProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProyectos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 420, 150));

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProveedores);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 420, 160));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 50, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 50, 10));

        jLabel4.setText("Nº total de piezas suministradas:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        totalPiezas.setEditable(false);
        totalPiezas.setBackground(new java.awt.Color(255, 255, 255));
        totalPiezas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalPiezas.setBorder(null);
        add(totalPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 70, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 70, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> codPieza;
    private javax.swing.JTextField infoPieza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField numProveedores;
    private javax.swing.JTextField numProyectos;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTable tablaProyectos;
    private javax.swing.JTextField totalPiezas;
    // End of variables declaration//GEN-END:variables
}
